/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as EventsIdRouteImport } from './routes/events/$id'
import { Route as ProjectsIdEventsRouteImport } from './routes/projects/$id.events'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdEventsRoute = ProjectsIdEventsRouteImport.update({
  id: '/projects/$id/events',
  path: '/projects/$id/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/events/$id': typeof EventsIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/events': typeof ProjectsIdEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/events/$id': typeof EventsIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id/events': typeof ProjectsIdEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/events/$id': typeof EventsIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/events': typeof ProjectsIdEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/events/$id'
    | '/projects/'
    | '/projects/$id/events'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test' | '/events/$id' | '/projects' | '/projects/$id/events'
  id:
    | '__root__'
    | '/'
    | '/test'
    | '/events/$id'
    | '/projects/'
    | '/projects/$id/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestRoute: typeof TestRoute
  EventsIdRoute: typeof EventsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsIdEventsRoute: typeof ProjectsIdEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/events': {
      id: '/projects/$id/events'
      path: '/projects/$id/events'
      fullPath: '/projects/$id/events'
      preLoaderRoute: typeof ProjectsIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestRoute: TestRoute,
  EventsIdRoute: EventsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsIdEventsRoute: ProjectsIdEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
