/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsCreateRouteImport } from './routes/projects/create'
import { Route as IssuesIdRouteImport } from './routes/issues/$id'
import { Route as EventsIdRouteImport } from './routes/events/$id'
import { Route as ProjectsIdSettingsRouteImport } from './routes/projects/$id.settings'
import { Route as ProjectsIdIssuesRouteImport } from './routes/projects/$id.issues'
import { Route as ProjectsIdEventsRouteImport } from './routes/projects/$id.events'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCreateRoute = ProjectsCreateRouteImport.update({
  id: '/projects/create',
  path: '/projects/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIdRoute = IssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdSettingsRoute = ProjectsIdSettingsRouteImport.update({
  id: '/projects/$id/settings',
  path: '/projects/$id/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdIssuesRoute = ProjectsIdIssuesRouteImport.update({
  id: '/projects/$id/issues',
  path: '/projects/$id/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdEventsRoute = ProjectsIdEventsRouteImport.update({
  id: '/projects/$id/events',
  path: '/projects/$id/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/events/$id': typeof EventsIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/events': typeof ProjectsIdEventsRoute
  '/projects/$id/issues': typeof ProjectsIdIssuesRoute
  '/projects/$id/settings': typeof ProjectsIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/events/$id': typeof EventsIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id/events': typeof ProjectsIdEventsRoute
  '/projects/$id/issues': typeof ProjectsIdIssuesRoute
  '/projects/$id/settings': typeof ProjectsIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/events/$id': typeof EventsIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/events': typeof ProjectsIdEventsRoute
  '/projects/$id/issues': typeof ProjectsIdIssuesRoute
  '/projects/$id/settings': typeof ProjectsIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/events/$id'
    | '/issues/$id'
    | '/projects/create'
    | '/projects/'
    | '/projects/$id/events'
    | '/projects/$id/issues'
    | '/projects/$id/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/events/$id'
    | '/issues/$id'
    | '/projects/create'
    | '/projects'
    | '/projects/$id/events'
    | '/projects/$id/issues'
    | '/projects/$id/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/events/$id'
    | '/issues/$id'
    | '/projects/create'
    | '/projects/'
    | '/projects/$id/events'
    | '/projects/$id/issues'
    | '/projects/$id/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  EventsIdRoute: typeof EventsIdRoute
  IssuesIdRoute: typeof IssuesIdRoute
  ProjectsCreateRoute: typeof ProjectsCreateRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsIdEventsRoute: typeof ProjectsIdEventsRoute
  ProjectsIdIssuesRoute: typeof ProjectsIdIssuesRoute
  ProjectsIdSettingsRoute: typeof ProjectsIdSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/create': {
      id: '/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof ProjectsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$id': {
      id: '/issues/$id'
      path: '/issues/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof IssuesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/settings': {
      id: '/projects/$id/settings'
      path: '/projects/$id/settings'
      fullPath: '/projects/$id/settings'
      preLoaderRoute: typeof ProjectsIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/issues': {
      id: '/projects/$id/issues'
      path: '/projects/$id/issues'
      fullPath: '/projects/$id/issues'
      preLoaderRoute: typeof ProjectsIdIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/events': {
      id: '/projects/$id/events'
      path: '/projects/$id/events'
      fullPath: '/projects/$id/events'
      preLoaderRoute: typeof ProjectsIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  EventsIdRoute: EventsIdRoute,
  IssuesIdRoute: IssuesIdRoute,
  ProjectsCreateRoute: ProjectsCreateRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsIdEventsRoute: ProjectsIdEventsRoute,
  ProjectsIdIssuesRoute: ProjectsIdIssuesRoute,
  ProjectsIdSettingsRoute: ProjectsIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
