/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as HybridRouteImport } from './routes/_hybrid'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as HybridIndexRouteImport } from './routes/_hybrid/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsCreateRouteImport } from './routes/_authenticated/projects/create'
import { Route as AuthenticatedIssuesIdRouteImport } from './routes/_authenticated/issues/$id'
import { Route as AuthenticatedEventsIdRouteImport } from './routes/_authenticated/events/$id'
import { Route as AuthenticatedProjectsIdSettingsRouteImport } from './routes/_authenticated/projects/$id.settings'
import { Route as AuthenticatedProjectsIdIssuesRouteImport } from './routes/_authenticated/projects/$id.issues'
import { Route as AuthenticatedProjectsIdEventsRouteImport } from './routes/_authenticated/projects/$id.events'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const HybridRoute = HybridRouteImport.update({
  id: '/_hybrid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const HybridIndexRoute = HybridIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HybridRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsCreateRoute =
  AuthenticatedProjectsCreateRouteImport.update({
    id: '/projects/create',
    path: '/projects/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIssuesIdRoute = AuthenticatedIssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsIdRoute = AuthenticatedEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIdSettingsRoute =
  AuthenticatedProjectsIdSettingsRouteImport.update({
    id: '/projects/$id/settings',
    path: '/projects/$id/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIdIssuesRoute =
  AuthenticatedProjectsIdIssuesRouteImport.update({
    id: '/projects/$id/issues',
    path: '/projects/$id/issues',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIdEventsRoute =
  AuthenticatedProjectsIdEventsRouteImport.update({
    id: '/projects/$id/events',
    path: '/projects/$id/events',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof HybridIndexRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/events/$id': typeof AuthenticatedEventsIdRoute
  '/issues/$id': typeof AuthenticatedIssuesIdRoute
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$id/events': typeof AuthenticatedProjectsIdEventsRoute
  '/projects/$id/issues': typeof AuthenticatedProjectsIdIssuesRoute
  '/projects/$id/settings': typeof AuthenticatedProjectsIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof HybridIndexRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/events/$id': typeof AuthenticatedEventsIdRoute
  '/issues/$id': typeof AuthenticatedIssuesIdRoute
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$id/events': typeof AuthenticatedProjectsIdEventsRoute
  '/projects/$id/issues': typeof AuthenticatedProjectsIdIssuesRoute
  '/projects/$id/settings': typeof AuthenticatedProjectsIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_hybrid': typeof HybridRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_hybrid/': typeof HybridIndexRoute
  '/_authenticated/events/$id': typeof AuthenticatedEventsIdRoute
  '/_authenticated/issues/$id': typeof AuthenticatedIssuesIdRoute
  '/_authenticated/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$id/events': typeof AuthenticatedProjectsIdEventsRoute
  '/_authenticated/projects/$id/issues': typeof AuthenticatedProjectsIdIssuesRoute
  '/_authenticated/projects/$id/settings': typeof AuthenticatedProjectsIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/events/$id'
    | '/issues/$id'
    | '/projects/create'
    | '/projects/'
    | '/projects/$id/events'
    | '/projects/$id/issues'
    | '/projects/$id/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/events/$id'
    | '/issues/$id'
    | '/projects/create'
    | '/projects'
    | '/projects/$id/events'
    | '/projects/$id/issues'
    | '/projects/$id/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_hybrid'
    | '/_public'
    | '/_public/login'
    | '/_public/register'
    | '/_hybrid/'
    | '/_authenticated/events/$id'
    | '/_authenticated/issues/$id'
    | '/_authenticated/projects/create'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$id/events'
    | '/_authenticated/projects/$id/issues'
    | '/_authenticated/projects/$id/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HybridRoute: typeof HybridRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hybrid': {
      id: '/_hybrid'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HybridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hybrid/': {
      id: '/_hybrid/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HybridIndexRouteImport
      parentRoute: typeof HybridRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/create': {
      id: '/_authenticated/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof AuthenticatedProjectsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/issues/$id': {
      id: '/_authenticated/issues/$id'
      path: '/issues/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof AuthenticatedIssuesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/$id': {
      id: '/_authenticated/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof AuthenticatedEventsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id/settings': {
      id: '/_authenticated/projects/$id/settings'
      path: '/projects/$id/settings'
      fullPath: '/projects/$id/settings'
      preLoaderRoute: typeof AuthenticatedProjectsIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id/issues': {
      id: '/_authenticated/projects/$id/issues'
      path: '/projects/$id/issues'
      fullPath: '/projects/$id/issues'
      preLoaderRoute: typeof AuthenticatedProjectsIdIssuesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id/events': {
      id: '/_authenticated/projects/$id/events'
      path: '/projects/$id/events'
      fullPath: '/projects/$id/events'
      preLoaderRoute: typeof AuthenticatedProjectsIdEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedEventsIdRoute: typeof AuthenticatedEventsIdRoute
  AuthenticatedIssuesIdRoute: typeof AuthenticatedIssuesIdRoute
  AuthenticatedProjectsCreateRoute: typeof AuthenticatedProjectsCreateRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedProjectsIdEventsRoute: typeof AuthenticatedProjectsIdEventsRoute
  AuthenticatedProjectsIdIssuesRoute: typeof AuthenticatedProjectsIdIssuesRoute
  AuthenticatedProjectsIdSettingsRoute: typeof AuthenticatedProjectsIdSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEventsIdRoute: AuthenticatedEventsIdRoute,
  AuthenticatedIssuesIdRoute: AuthenticatedIssuesIdRoute,
  AuthenticatedProjectsCreateRoute: AuthenticatedProjectsCreateRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedProjectsIdEventsRoute: AuthenticatedProjectsIdEventsRoute,
  AuthenticatedProjectsIdIssuesRoute: AuthenticatedProjectsIdIssuesRoute,
  AuthenticatedProjectsIdSettingsRoute: AuthenticatedProjectsIdSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface HybridRouteChildren {
  HybridIndexRoute: typeof HybridIndexRoute
}

const HybridRouteChildren: HybridRouteChildren = {
  HybridIndexRoute: HybridIndexRoute,
}

const HybridRouteWithChildren =
  HybridRoute._addFileChildren(HybridRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HybridRoute: HybridRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
